import { HospitalMaster, MedicineItem, DynamicForm, MonthlyProgressReport, MedicineDemandResponse, ActivityLog } from '../types';

export const INITIAL_HOSPITALS: HospitalMaster[] = [
  { id: 'DDN001', hospital_name: 'Sahastradhara', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN001', assigned_password: 'ayush@123' },
  { id: 'DDN002', hospital_name: 'Ambiwala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN002', assigned_password: 'ayush@123' },
  { id: 'DDN003', hospital_name: 'Jassowala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN003', assigned_password: 'ayush@123' },
  { id: 'DDN004', hospital_name: 'Horawala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN004', assigned_password: 'ayush@123' },
  { id: 'DDN005', hospital_name: 'Jisau', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN005', assigned_password: 'ayush@123' },
  { id: 'DDN006', hospital_name: 'Jollygrant', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN006', assigned_password: 'ayush@123' },
  { id: 'DDN007', hospital_name: 'Kyara', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN007', assigned_password: 'ayush@123' },
  { id: 'DDN008', hospital_name: 'Niranjanpur', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN008', assigned_password: 'ayush@123' },
  { id: 'DDN009', hospital_name: 'Bullawala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN009', assigned_password: 'ayush@123' },
  { id: 'DDN010', hospital_name: 'Itharna', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN010', assigned_password: 'ayush@123' },
  { id: 'DDN011', hospital_name: 'Kota', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN011', assigned_password: 'ayush@123' },
  { id: 'DDN012', hospital_name: 'Kerad', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN012', assigned_password: 'ayush@123' },
  { id: 'DDN013', hospital_name: 'Langha', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN013', assigned_password: 'ayush@123' },
  { id: 'DDN014', hospital_name: 'Nagthat', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN014', assigned_password: 'ayush@123' },
  { id: 'DDN015', hospital_name: 'Bhatta', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN015', assigned_password: 'ayush@123' },
  { id: 'DDN016', hospital_name: 'Maindal', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN016', assigned_password: 'ayush@123' },
  { id: 'DDN017', hospital_name: 'Kunain', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN017', assigned_password: 'ayush@123' },
  { id: 'DDN018', hospital_name: 'Majri Mafi', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN018', assigned_password: 'ayush@123' },
  { id: 'DDN019', hospital_name: 'Bhandaribagh', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN019', assigned_password: 'ayush@123' },
  { id: 'DDN020', hospital_name: 'Vidholi', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN020', assigned_password: 'ayush@123' },
  { id: 'DDN021', hospital_name: 'Selaqui', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN021', assigned_password: 'ayush@123' },
  { id: 'DDN022', hospital_name: 'Rajawala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN022', assigned_password: 'ayush@123' },
  { id: 'DDN023', hospital_name: 'Bhaniyawala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN023', assigned_password: 'ayush@123' },
  { id: 'DDN024', hospital_name: 'Majri Grant', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN024', assigned_password: 'ayush@123' },
  { id: 'DDN025', hospital_name: 'Majra', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN025', assigned_password: 'ayush@123' },
  { id: 'DDN026', hospital_name: 'Nathuwawala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN026', assigned_password: 'ayush@123' },
  { id: 'DDN027', hospital_name: 'Dholas', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN027', assigned_password: 'ayush@123' },
  { id: 'DDN028', hospital_name: 'Sediya', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN028', assigned_password: 'ayush@123' },
  { id: 'DDN029', hospital_name: 'Deu', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN029', assigned_password: 'ayush@123' },
  { id: 'DDN030', hospital_name: 'Koptimarlu', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN030', assigned_password: 'ayush@123' },
  { id: 'DDN031', hospital_name: 'Dharampur', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN031', assigned_password: 'ayush@123' },
  { id: 'DDN032', hospital_name: 'Chidiyamandi', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN032', assigned_password: 'ayush@123' },
  { id: 'DDN033', hospital_name: 'Kuwasi', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN033', assigned_password: 'ayush@123' },
  { id: 'DDN034', hospital_name: 'Gujrada', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN034', assigned_password: 'ayush@123' },
  { id: 'DDN035', hospital_name: 'Rishikesh', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN035', assigned_password: 'ayush@123' },
  { id: 'DDN036', hospital_name: 'Kimadiplat', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN036', assigned_password: 'ayush@123' },
  { id: 'DDN037', hospital_name: 'Lakhamandal', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN037', assigned_password: 'ayush@123' },
  { id: 'DDN038', hospital_name: 'Barothan', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN038', assigned_password: 'ayush@123' },
  { id: 'DDN039', hospital_name: 'Matiyawa', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN039', assigned_password: 'ayush@123' },
  { id: 'DDN040', hospital_name: 'Chilhard', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN040', assigned_password: 'ayush@123' },
  { id: 'DDN041', hospital_name: 'Miyawala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN041', assigned_password: 'ayush@123' },
  { id: 'DDN042', hospital_name: 'Jhajra', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN042', assigned_password: 'ayush@123' },
  { id: 'DDN043', hospital_name: 'Herbertpur', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN043', assigned_password: 'ayush@123' },
  { id: 'DDN044', hospital_name: 'Sachivalay', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN044', assigned_password: 'ayush@123' },
  { id: 'DDN045', hospital_name: 'Rajbhawan', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN045', assigned_password: 'ayush@123' },
  { id: 'DDN046', hospital_name: 'Bhauwala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN046', assigned_password: 'ayush@123' },
  { id: 'DDN047', hospital_name: 'Mothorowala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN047', assigned_password: 'ayush@123' },
  { id: 'DDN048', hospital_name: 'Kandoli', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN048', assigned_password: 'ayush@123' },
  { id: 'DDN049', hospital_name: 'Gangro', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN049', assigned_password: 'ayush@123' },
  { id: 'DDN050', hospital_name: 'Nagau', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN050', assigned_password: 'ayush@123' },
  { id: 'DDN051', hospital_name: 'Kwanu', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN051', assigned_password: 'ayush@123' },
  { id: 'DDN052', hospital_name: 'Darmigard', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN052', assigned_password: 'ayush@123' },
  { id: 'DDN053', hospital_name: 'Vidhansabha', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN053', assigned_password: 'ayush@123' },
  { id: 'DDN054', hospital_name: 'DH Male hospital', category: 'District Hospital', block_name: 'District Hospital', uid: 'DDN054', assigned_password: 'ayush@123' },
  { id: 'DDN055', hospital_name: 'DH Female hospital', category: 'District Hospital', block_name: 'District Hospital', uid: 'DDN055', assigned_password: 'ayush@123' },
  { id: 'DDN056', hospital_name: 'Barotha', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN056', assigned_password: 'ayush@123' },
  { id: 'DDN057', hospital_name: 'Bhataad', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN057', assigned_password: 'ayush@123' },
  { id: 'DDN058', hospital_name: 'Pingiri', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN058', assigned_password: 'ayush@123' },
  { id: 'DDN059', hospital_name: 'Kotikansar', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN059', assigned_password: 'ayush@123' },
  { id: 'DDN060', hospital_name: 'Manthat', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN060', assigned_password: 'ayush@123' },
  { id: 'DDN061', hospital_name: 'Dasau', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN061', assigned_password: 'ayush@123' },
  { id: 'DDN062', hospital_name: 'Bulhad', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN062', assigned_password: 'ayush@123' },
  { id: 'DDN063', hospital_name: 'Koti Sahaspur', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN063', assigned_password: 'ayush@123' },
  { id: 'DDN064', hospital_name: 'Khabau', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN064', assigned_password: 'ayush@123' },
  { id: 'DDN065', hospital_name: 'Nahikala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN065', assigned_password: 'ayush@123' },
  { id: 'DDN066', hospital_name: 'Sarona', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN066', assigned_password: 'ayush@123' },
  { id: 'DDN067', hospital_name: 'Thaina', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN067', assigned_password: 'ayush@123' },
  { id: 'DDN068', hospital_name: 'Brimau', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN068', assigned_password: 'ayush@123' },
  { id: 'DDN069', hospital_name: 'Kamla', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN069', assigned_password: 'ayush@123' },
  { id: 'DDN070', hospital_name: 'Mairawana', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN070', assigned_password: 'ayush@123' },
  { id: 'DDN071', hospital_name: 'Katapathar', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN071', assigned_password: 'ayush@123' },
  { id: 'DDN072', hospital_name: 'Hatal', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN072', assigned_password: 'ayush@123' },
  { id: 'DDN073', hospital_name: 'Bhagwantpur', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN073', assigned_password: 'ayush@123' },
  { id: 'DDN074', hospital_name: 'Balawala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN074', assigned_password: 'ayush@123' },
  { id: 'DDN075', hospital_name: 'Paschimwala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN075', assigned_password: 'ayush@123' },
  { id: 'DDN076', hospital_name: 'Nayagaon', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN076', assigned_password: 'ayush@123' },
  { id: 'DDN077', hospital_name: 'Nehrugram', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN077', assigned_password: 'ayush@123' },
  { id: 'DDN078', hospital_name: 'Mehuwala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN078', assigned_password: 'ayush@123' },
  { id: 'DDN079', hospital_name: 'Chiderwala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN079', assigned_password: 'ayush@123' },
  { id: 'DDN080', hospital_name: 'Dhoodli', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN080', assigned_password: 'ayush@123' },
  { id: 'DDN081', hospital_name: 'Doiwala', category: 'CHC / PHC / Ayush Wing', block_name: 'CHC / PHC / Ayush Wing', uid: 'DDN081', assigned_password: 'ayush@123' },
  { id: 'DDN082', hospital_name: 'Sahiya', category: 'CHC / PHC / Ayush Wing', block_name: 'CHC / PHC / Ayush Wing', uid: 'DDN082', assigned_password: 'ayush@123' },
  { id: 'DDN083', hospital_name: 'Musoorie', category: 'CHC / PHC / Ayush Wing', block_name: 'CHC / PHC / Ayush Wing', uid: 'DDN083', assigned_password: 'ayush@123' },
  { id: 'DDN084', hospital_name: 'Kalsi', category: 'CHC / PHC / Ayush Wing', block_name: 'CHC / PHC / Ayush Wing', uid: 'DDN084', assigned_password: 'ayush@123' },
  { id: 'DDN085', hospital_name: 'Rudrapur', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN085', assigned_password: 'ayush@123' },
  { id: 'DDN086', hospital_name: 'Thano', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN086', assigned_password: 'ayush@123' },
  { id: 'DDN087', hospital_name: 'Raiwala', category: 'State Ayurvedic Dispensary', block_name: 'State Ayurvedic Dispensary', uid: 'DDN087', assigned_password: 'ayush@123' },
];



export const INITIAL_MEDICINES: MedicineItem[] = [
  // Classical Medicines (20)
  { id: 'med-c01', category: 'Classical Medicine', medicine_name: 'Triphala Churna', pack_size: '100 gm' },
  { id: 'med-c02', category: 'Classical Medicine', medicine_name: 'Sitopaladi Churna', pack_size: '60 gm' },
  { id: 'med-c03', category: 'Classical Medicine', medicine_name: 'Ashwagandharishta', pack_size: '450 ml' },
  { id: 'med-c04', category: 'Classical Medicine', medicine_name: 'Draksharishta', pack_size: '450 ml' },
  { id: 'med-c05', category: 'Classical Medicine', medicine_name: 'Amritarishta', pack_size: '450 ml' },
  { id: 'med-c06', category: 'Classical Medicine', medicine_name: 'Dashmularishta', pack_size: '450 ml' },
  { id: 'med-c07', category: 'Classical Medicine', medicine_name: 'Chyawanprash Awaleha', pack_size: '500 gm' },
  { id: 'med-c08', category: 'Classical Medicine', medicine_name: 'Khadiradi Vati', pack_size: '40 tab' },
  { id: 'med-c09', category: 'Classical Medicine', medicine_name: 'Sanjivani Vati', pack_size: '40 tab' },
  { id: 'med-c10', category: 'Classical Medicine', medicine_name: 'Arogyavardhini Vati', pack_size: '40 tab' },
  { id: 'med-c11', category: 'Classical Medicine', medicine_name: 'Chandraprabha Vati', pack_size: '40 tab' },
  { id: 'med-c12', category: 'Classical Medicine', medicine_name: 'Yograj Guggulu', pack_size: '40 tab' },
  { id: 'med-c13', category: 'Classical Medicine', medicine_name: 'Kaishore Guggulu', pack_size: '40 tab' },
  { id: 'med-c14', category: 'Classical Medicine', medicine_name: 'Mahanarayan Taila', pack_size: '100 ml' },
  { id: 'med-c15', category: 'Classical Medicine', medicine_name: 'Pinda Taila', pack_size: '100 ml' },
  { id: 'med-c16', category: 'Classical Medicine', medicine_name: 'Kasis Bhasma', pack_size: '10 gm' },
  { id: 'med-c17', category: 'Classical Medicine', medicine_name: 'Shankh Bhasma', pack_size: '10 gm' },
  { id: 'med-c18', category: 'Classical Medicine', medicine_name: 'Hingwashtak Churna', pack_size: '100 gm' },
  { id: 'med-c19', category: 'Classical Medicine', medicine_name: 'Avipattikar Churna', pack_size: '100 gm' },
  { id: 'med-c20', category: 'Classical Medicine', medicine_name: 'Mahasudarshan Churna', pack_size: '100 gm' },

  // Official Patent Medicines List 1 (84 Formulations)
  { id: 'med-p01', category: 'Patent Medicine', medicine_name: 'Amavatari cap', pack_size: '40 cap' },
  { id: 'med-p02', category: 'Patent Medicine', medicine_name: 'Colokam Tab', pack_size: '20 tab' },
  { id: 'med-p03', category: 'Patent Medicine', medicine_name: 'Myelotone Tab.', pack_size: '40 tab' },
  { id: 'med-p04', category: 'Patent Medicine', medicine_name: 'Throat c Tab.', pack_size: '40 tab' },
  { id: 'med-p05', category: 'Patent Medicine', medicine_name: 'Mellit Tab', pack_size: '40 tab' },
  { id: 'med-p06', category: 'Patent Medicine', medicine_name: 'Madhumehari Churna', pack_size: '100 Gm' },
  { id: 'med-p07', category: 'Patent Medicine', medicine_name: 'Tensonil Tab', pack_size: '40 Tab' },
  { id: 'med-p08', category: 'Patent Medicine', medicine_name: 'Rhumavin cap.', pack_size: '40 cap' },
  { id: 'med-p09', category: 'Patent Medicine', medicine_name: 'Spasonil Tab.', pack_size: '40 tab' },
  { id: 'med-p10', category: 'Patent Medicine', medicine_name: 'Medha Tab', pack_size: '40 tab' },
  { id: 'med-p11', category: 'Patent Medicine', medicine_name: 'Uricare Tab.', pack_size: '40 tab' },
  { id: 'med-p12', category: 'Patent Medicine', medicine_name: 'Uisacid Tab.', pack_size: '40 tab' },
  { id: 'med-p13', category: 'Patent Medicine', medicine_name: 'Dysentil Plus Tab', pack_size: '20 Tab' },
  { id: 'med-p14', category: 'Patent Medicine', medicine_name: 'Rheumalin Tab.', pack_size: '40 tab' },
  { id: 'med-p15', category: 'Patent Medicine', medicine_name: 'Hrideshu Tab.', pack_size: '40 tab' },
  { id: 'med-p16', category: 'Patent Medicine', medicine_name: 'Remedin Tab.', pack_size: '40 tab' },
  { id: 'med-p17', category: 'Patent Medicine', medicine_name: 'Karansudha Drops', pack_size: '10 ML' },
  { id: 'med-p18', category: 'Patent Medicine', medicine_name: 'Prostol Tab.', pack_size: '40 tab' },
  { id: 'med-p19', category: 'Patent Medicine', medicine_name: 'Shilapex Tab.', pack_size: '40 tab' },
  { id: 'med-p20', category: 'Patent Medicine', medicine_name: 'Tenz off cap.', pack_size: '40 cap' },
  { id: 'med-p21', category: 'Patent Medicine', medicine_name: 'Realzyme Tab', pack_size: '40 cap' },
  { id: 'med-p22', category: 'Patent Medicine', medicine_name: 'Arshonyl Tab', pack_size: '40 Tab' },
  { id: 'med-p23', category: 'Patent Medicine', medicine_name: 'Feritone Syp.', pack_size: '100 ML' },
  { id: 'med-p24', category: 'Patent Medicine', medicine_name: 'Rheumo Oil', pack_size: '20 ML' },
  { id: 'med-p25', category: 'Patent Medicine', medicine_name: 'Kofnil Syp.', pack_size: '100 ML' },
  { id: 'med-p26', category: 'Patent Medicine', medicine_name: 'Kofnil SF Syp.', pack_size: '100 ML' },
  { id: 'med-p27', category: 'Patent Medicine', medicine_name: 'Krimihar Syp', pack_size: '100 ml' },
  { id: 'med-p28', category: 'Patent Medicine', medicine_name: 'Crush Tab', pack_size: '40 cap' },
  { id: 'med-p29', category: 'Patent Medicine', medicine_name: 'Fetone Syp.', pack_size: '100 ML' },
  { id: 'med-p30', category: 'Patent Medicine', medicine_name: 'Pure-Up-Syp.', pack_size: '100 ML' },
  { id: 'med-p31', category: 'Patent Medicine', medicine_name: 'Vitamrit SF Syp.', pack_size: '100 ML' },
  { id: 'med-p32', category: 'Patent Medicine', medicine_name: 'Rheumo Pravhi Syp.', pack_size: '100 ML' },
  { id: 'med-p33', category: 'Patent Medicine', medicine_name: 'Uritab Tab.', pack_size: '40 Tab' },
  { id: 'med-p34', category: 'Patent Medicine', medicine_name: 'Shwasi Avaleha', pack_size: '100 GM' },
  { id: 'med-p35', category: 'Patent Medicine', medicine_name: 'Brainton Syp.', pack_size: '100 ML' },
  { id: 'med-p36', category: 'Patent Medicine', medicine_name: 'Rechak Syp.', pack_size: '100 ML' },
  { id: 'med-p37', category: 'Patent Medicine', medicine_name: 'Crush-RT- SF-SYP.', pack_size: '100 ML' },
  { id: 'med-p38', category: 'Patent Medicine', medicine_name: 'G-Amrita-Cap', pack_size: '40 Cap.' },
  { id: 'med-p39', category: 'Patent Medicine', medicine_name: 'LivoSyp Tab', pack_size: '40 Cap.' },
  { id: 'med-p40', category: 'Patent Medicine', medicine_name: 'Dysen-Cure Syp', pack_size: '100 ML' },
  { id: 'med-p41', category: 'Patent Medicine', medicine_name: 'Granthika Cap', pack_size: '40 cap' },
  { id: 'med-p42', category: 'Patent Medicine', medicine_name: 'Baijnath Arshoghan Syp.', pack_size: '100 ml' },
  { id: 'med-p43', category: 'Patent Medicine', medicine_name: 'Asthi Sanhari Cap', pack_size: '40 tab' },
  { id: 'med-p44', category: 'Patent Medicine', medicine_name: 'Shigru Plus Tab', pack_size: '40 TAb' },
  { id: 'med-p45', category: 'Patent Medicine', medicine_name: 'Arjun-Plus Syp.', pack_size: '100 ml' },
  { id: 'med-p46', category: 'Patent Medicine', medicine_name: 'Cardio Care Cap', pack_size: '40 Cap' },
  { id: 'med-p47', category: 'Patent Medicine', medicine_name: 'Panch Ras Rasayan', pack_size: '100 ml' },
  { id: 'med-p48', category: 'Patent Medicine', medicine_name: 'Slimtone Tab', pack_size: '40 tab' },
  { id: 'med-p49', category: 'Patent Medicine', medicine_name: 'Baijnath caleule Syp.', pack_size: '100 ml' },
  { id: 'med-p50', category: 'Patent Medicine', medicine_name: 'Anita Vati Without Ras Sindura', pack_size: '40 tab' },
  { id: 'med-p51', category: 'Patent Medicine', medicine_name: 'Livo Haemostant Syp.', pack_size: '100 ML' },
  { id: 'med-p52', category: 'Patent Medicine', medicine_name: 'Shirishasva', pack_size: '100 ML' },
  { id: 'med-p53', category: 'Patent Medicine', medicine_name: 'Shigru Guggulu Tab. Without Ras Sindura', pack_size: '40 Tab' },
  { id: 'med-p54', category: 'Patent Medicine', medicine_name: 'E-Brim Tab', pack_size: '20 Tab' },
  { id: 'med-p55', category: 'Patent Medicine', medicine_name: 'Memofast SYP.', pack_size: '100 ML' },
  { id: 'med-p56', category: 'Patent Medicine', medicine_name: 'karnani Janam Ghutti', pack_size: '100 ML' },
  { id: 'med-p57', category: 'Patent Medicine', medicine_name: 'Hazmee Drops', pack_size: '20 ML' },
  { id: 'med-p58', category: 'Patent Medicine', medicine_name: 'Neemsudha Syp.', pack_size: '100 ML' },
  { id: 'med-p59', category: 'Patent Medicine', medicine_name: 'Rheuma Forte Oil', pack_size: '20 ML' },
  { id: 'med-p60', category: 'Patent Medicine', medicine_name: 'Tulsi Cough Syp', pack_size: '100 ML' },
  { id: 'med-p61', category: 'Patent Medicine', medicine_name: 'Superzyme Syp.', pack_size: '100 ML' },
  { id: 'med-p62', category: 'Patent Medicine', medicine_name: 'Laxid Syp.', pack_size: '100 ML' },
  { id: 'med-p63', category: 'Patent Medicine', medicine_name: 'Liv Samrat Syp.', pack_size: '100 ML' },
  { id: 'med-p64', category: 'Patent Medicine', medicine_name: 'Rhumed Ointment', pack_size: '20gm' },
  { id: 'med-p65', category: 'Patent Medicine', medicine_name: 'Mulzyme Syp.', pack_size: '100 ml' },
  { id: 'med-p66', category: 'Patent Medicine', medicine_name: 'pachmeena Tonic', pack_size: '100 ml' },
  { id: 'med-p67', category: 'Patent Medicine', medicine_name: 'Brainton Tab.', pack_size: '40 tab' },
  { id: 'med-p68', category: 'Patent Medicine', medicine_name: 'Rhumed SG Tab', pack_size: '40 tab' },
  { id: 'med-p69', category: 'Patent Medicine', medicine_name: 'Kuka Caugh Tab.', pack_size: '40 tab' },
  { id: 'med-p70', category: 'Patent Medicine', medicine_name: 'Kasgo Syp.', pack_size: '100 ml' },
  { id: 'med-p71', category: 'Patent Medicine', medicine_name: 'Iromin Cap.', pack_size: '40 cap' },
  { id: 'med-p72', category: 'Patent Medicine', medicine_name: 'Diabetes Strong cap.', pack_size: '40 cap' },
  { id: 'med-p73', category: 'Patent Medicine', medicine_name: 'Sarvin Tab.', pack_size: '40 tab' },
  { id: 'med-p74', category: 'Patent Medicine', medicine_name: 'Asthmin cap.', pack_size: '40 cap' },
  { id: 'med-p75', category: 'Patent Medicine', medicine_name: 'Triphala Tab.', pack_size: '20Tab' },
  { id: 'med-p76', category: 'Patent Medicine', medicine_name: 'Muliv Strong Tab.', pack_size: '40 tab' },
  { id: 'med-p77', category: 'Patent Medicine', medicine_name: 'Livrhex Cap.', pack_size: '40 Cap' },
  { id: 'med-p78', category: 'Patent Medicine', medicine_name: 'Ayuimu', pack_size: '40 tab' },
  { id: 'med-p79', category: 'Patent Medicine', medicine_name: 'Liv 52 Syp.', pack_size: '100 ML' },
  { id: 'med-p80', category: 'Patent Medicine', medicine_name: 'Bresol Syp.', pack_size: '100 gm' },
  { id: 'med-p81', category: 'Patent Medicine', medicine_name: 'Evecare', pack_size: '100 ML' },
  { id: 'med-p82', category: 'Patent Medicine', medicine_name: 'Sepnil Syp.', pack_size: '100 ml' },
  { id: 'med-p83', category: 'Patent Medicine', medicine_name: 'Tringasav Plus Syp.', pack_size: '100 ml' },
  { id: 'med-p84', category: 'Patent Medicine', medicine_name: 'Amlax Granules', pack_size: '100 GM' }
];

export const INITIAL_DYNAMIC_FORMS: DynamicForm[] = [
  {
    id: 'form-monsoon-2026',
    form_title: 'Monsoon Disease Preparedness & Stock Audit 2026',
    description: 'Special administrative audit by District Ayurvedic Officer Dehradun regarding availability of emergency fever medicines, ORS, water chlorination, and vector-borne illness preparedness.',
    is_active: true,
    created_at: '2026-08-01T10:00:00Z',
    form_fields: [
      {
        id: 'emergency_stock_status',
        label: 'Status of Emergency Fever & Diarrhea Medicines',
        type: 'select',
        options: ['Adequate (>30 days)', 'Moderate (15-30 days)', 'Critical Shortage (<15 days)'],
        required: true,
      },
      {
        id: 'water_purification_tablets',
        label: 'Chlorine / Halazone Tablets Available (Count in units)',
        type: 'number',
        required: true,
        placeholder: 'e.g. 500',
      },
      {
        id: 'dengue_chikungunya_cases',
        label: 'Total Suspected Vector-Borne Cases Treated This Month',
        type: 'number',
        required: true,
        placeholder: '0',
      },
      {
        id: 'panchakarma_equipment_operational',
        label: 'Are Panchakarma Droni & Steam Chambers Fully Operational?',
        type: 'select',
        options: ['Yes - Fully Functional', 'Partially Functional', 'Requires Maintenance', 'Not Installed'],
        required: true,
      },
      {
        id: 'inspection_remarks',
        label: 'Infrastructure Remarks / Urgent Requirements',
        type: 'textarea',
        required: false,
        placeholder: 'Mention building condition, water supply, electricity or emergency staff needs...',
      },
    ],
  },
];

export const INITIAL_MPR_REPORTS: MonthlyProgressReport[] = [
  {
    id: 'mpr-001',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    month_year: '2026-08',
    opd_count: 1420,
    panchakarma_count: 310,
    officer_name: 'Dr. Ramesh Chandra Nautiyal (AMO)',
    submitted_at: '2026-09-02T11:20:00Z',
    other_metrics: {
      opd_male: 580,
      opd_female: 690,
      opd_child: 150,
      ipd_admissions: 45,
      bed_occupancy_days: 280,
      yoga_participants: 620,
      ayush_camps_conducted: 4,
      snehan_swedan: 140,
      basti_karma: 85,
      nasya_karma: 45,
      shirodhara: 40,
      remarks: 'High patient load for joint disorders and seasonal viral fever.',
    },
  },
  {
    id: 'mpr-002',
    hospital_id: 'hosp-002',
    hospital_name: 'Government Ayurvedic Hospital, Rishikesh',
    month_year: '2026-08',
    opd_count: 1180,
    panchakarma_count: 245,
    officer_name: 'Dr. Anjali Uniyal (Sr. Medical Officer)',
    submitted_at: '2026-09-03T14:45:00Z',
    other_metrics: {
      opd_male: 510,
      opd_female: 540,
      opd_child: 130,
      ipd_admissions: 32,
      bed_occupancy_days: 190,
      yoga_participants: 480,
      ayush_camps_conducted: 3,
      snehan_swedan: 110,
      basti_karma: 65,
      nasya_karma: 38,
      shirodhara: 32,
      remarks: 'Special monsoon health awareness camps conducted along Ganga ghats.',
    },
  },
  {
    id: 'mpr-003',
    hospital_id: 'hosp-003',
    hospital_name: 'Government Ayurvedic Dispensary, Vikasnagar',
    month_year: '2026-08',
    opd_count: 760,
    panchakarma_count: 90,
    officer_name: 'Dr. Vikram Singh Rawat',
    submitted_at: '2026-09-04T10:15:00Z',
    other_metrics: {
      opd_male: 340,
      opd_female: 350,
      opd_child: 70,
      ipd_admissions: 0,
      yoga_participants: 210,
      ayush_camps_conducted: 2,
      snehan_swedan: 50,
      basti_karma: 25,
      nasya_karma: 15,
      remarks: 'Dispensed preventive kwath for rainy season.',
    },
  },
];

export const INITIAL_DEMANDS: MedicineDemandResponse[] = [
  {
    id: 'dem-001',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    medicine_id: 'med-c01',
    medicine_name: 'Triphala Churna',
    category: 'Classical Medicine',
    pack_size: '100 gm',
    requested_quantity: 150,
    officer_name: 'Dr. Ramesh Chandra Nautiyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'dem-002',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    medicine_id: 'med-c03',
    medicine_name: 'Ashwagandharishta',
    category: 'Classical Medicine',
    pack_size: '450 ml',
    requested_quantity: 80,
    officer_name: 'Dr. Ramesh Chandra Nautiyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'dem-003',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    medicine_id: 'med-p01',
    medicine_name: 'Liver Protective Syrup (Hepato-Tonic)',
    category: 'Patent Medicine',
    pack_size: '200 ml',
    requested_quantity: 120,
    officer_name: 'Dr. Ramesh Chandra Nautiyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'dem-004',
    hospital_id: 'hosp-002',
    hospital_name: 'Government Ayurvedic Hospital, Rishikesh',
    medicine_id: 'med-c01',
    medicine_name: 'Triphala Churna',
    category: 'Classical Medicine',
    pack_size: '100 gm',
    requested_quantity: 100,
    officer_name: 'Dr. Anjali Uniyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-29T15:30:00Z',
  },
  {
    id: 'dem-005',
    hospital_id: 'hosp-002',
    hospital_name: 'Government Ayurvedic Hospital, Rishikesh',
    medicine_id: 'med-p02',
    medicine_name: 'Joint Pain Relief Liniment/Oil',
    category: 'Patent Medicine',
    pack_size: '60 ml',
    requested_quantity: 90,
    officer_name: 'Dr. Anjali Uniyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-29T15:30:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-01',
    action: 'Medicine Demand Catalog Published',
    details: 'Uploaded 20 Classical and 14 Patent items for Annual Demand 2026-2027',
    user: 'District Ayurvedic Officer (Admin)',
    timestamp: '2026-08-15T09:00:00Z',
    category: 'medicine',
  },
  {
    id: 'log-02',
    action: 'Special Survey Form Published',
    details: 'Monsoon Disease Preparedness & Stock Audit 2026 made active',
    user: 'District Ayurvedic Officer (Admin)',
    timestamp: '2026-08-16T11:30:00Z',
    category: 'form',
  },
  {
    id: 'log-03',
    action: 'Medicine Demand Submitted',
    details: 'Submitted demand for 3 items (350 total units)',
    user: 'District Ayurvedic Hospital, Tilak Road (Dr. Ramesh Chandra Nautiyal)',
    timestamp: '2026-08-28T12:00:00Z',
    category: 'medicine',
  },
  {
    id: 'log-04',
    action: 'Medicine Demand Submitted',
    details: 'Submitted demand for 2 items (190 total units)',
    user: 'Government Ayurvedic Hospital, Rishikesh (Dr. Anjali Uniyal)',
    timestamp: '2026-08-29T15:30:00Z',
    category: 'medicine',
  },
  {
    id: 'log-05',
    action: 'MPR Report Submitted',
    details: 'Submitted Monthly Progress Report for August 2026 (OPD: 1420, Panchakarma: 310)',
    user: 'District Ayurvedic Hospital, Tilak Road (Dr. Ramesh Chandra Nautiyal)',
    timestamp: '2026-09-02T11:20:00Z',
    category: 'mpr',
  },
];
