import { HospitalMaster, MedicineItem, DynamicForm, MonthlyProgressReport, MedicineDemandResponse, ActivityLog } from '../types';

export const INITIAL_HOSPITALS: HospitalMaster[] = [
  {
    id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    assigned_password: 'ayush@dehradun1',
    block_name: 'Dehradun Sadar',
    contact_phone: '+91 135-2654321',
  },
  {
    id: 'hosp-002',
    hospital_name: 'Government Ayurvedic Hospital, Rishikesh',
    assigned_password: 'ayush@rishi2',
    block_name: 'Rishikesh',
    contact_phone: '+91 135-2430123',
  },
  {
    id: 'hosp-003',
    hospital_name: 'Government Ayurvedic Dispensary, Vikasnagar',
    assigned_password: 'ayush@vikas3',
    block_name: 'Vikasnagar',
    contact_phone: '+91 136-0251122',
  },
  {
    id: 'hosp-004',
    hospital_name: 'Government Ayurvedic Hospital, Chakrata',
    assigned_password: 'ayush@chak4',
    block_name: 'Chakrata',
    contact_phone: '+91 136-0275440',
  },
  {
    id: 'hosp-005',
    hospital_name: 'Government Ayurvedic Dispensary, Doiwala',
    assigned_password: 'ayush@doi5',
    block_name: 'Doiwala',
    contact_phone: '+91 135-2695511',
  },
  {
    id: 'hosp-006',
    hospital_name: 'Government Ayurvedic Dispensary, Sahaspur',
    assigned_password: 'ayush@sahas6',
    block_name: 'Sahaspur',
    contact_phone: '+91 135-2773210',
  },
  {
    id: 'hosp-007',
    hospital_name: 'Government Ayurvedic Dispensary, Kalsi',
    assigned_password: 'ayush@kalsi7',
    block_name: 'Kalsi',
    contact_phone: '+91 136-0271100',
  },
  {
    id: 'hosp-008',
    hospital_name: 'Government Ayurvedic Dispensary, Raipur',
    assigned_password: 'ayush@raipur8',
    block_name: 'Raipur',
    contact_phone: '+91 135-2780998',
  },
  {
    id: 'hosp-009',
    hospital_name: 'Government Ayurvedic Dispensary, Mussoorie',
    assigned_password: 'ayush@muss9',
    block_name: 'Mussoorie',
    contact_phone: '+91 135-2632115',
  },
  {
    id: 'hosp-010',
    hospital_name: 'Government Ayurvedic Dispensary, Premnagar',
    assigned_password: 'ayush@prem10',
    block_name: 'Sahaspur',
    contact_phone: '+91 135-2774500',
  },
  {
    id: 'hosp-011',
    hospital_name: 'Government Unani Dispensary, Dehradun City',
    assigned_password: 'unani@ddn11',
    block_name: 'Dehradun Sadar',
    contact_phone: '+91 135-2621090',
  },
  {
    id: 'hosp-012',
    hospital_name: 'Government Ayurvedic Dispensary, Tyuni',
    assigned_password: 'ayush@tyuni12',
    block_name: 'Chakrata',
    contact_phone: '+91 136-0284300',
  },
  {
    id: 'hosp-013',
    hospital_name: 'Government Ayurvedic Dispensary, Selaqui',
    assigned_password: 'ayush@selaqui13',
    block_name: 'Sahaspur',
    contact_phone: '+91 135-2698744',
  },
  {
    id: 'hosp-014',
    hospital_name: 'Government Ayurvedic Dispensary, Clement Town',
    assigned_password: 'ayush@clement14',
    block_name: 'Dehradun Sadar',
    contact_phone: '+91 135-2645001',
  },
  {
    id: 'hosp-015',
    hospital_name: 'Government Ayurvedic Dispensary, Bhogpur',
    assigned_password: 'ayush@bhogpur15',
    block_name: 'Doiwala',
    contact_phone: '+91 135-2692233',
  },
];

export const INITIAL_MEDICINES: MedicineItem[] = [
  // Classical Medicines
  { id: 'med-c01', category: 'Classical Medicine', medicine_name: 'Triphala Churna', pack_size: '100 gm' },
  { id: 'med-c02', category: 'Classical Medicine', medicine_name: 'Sitopaladi Churna', pack_size: '60 gm' },
  { id: 'med-c03', category: 'Classical Medicine', medicine_name: 'Ashwagandharishta', pack_size: '450 ml' },
  { id: 'med-c04', category: 'Classical Medicine', medicine_name: 'Draksharishta', pack_size: '450 ml' },
  { id: 'med-c05', category: 'Classical Medicine', medicine_name: 'Amritarishta', pack_size: '450 ml' },
  { id: 'med-c06', category: 'Classical Medicine', medicine_name: 'Dashmularishta', pack_size: '450 ml' },
  { id: 'med-c07', category: 'Classical Medicine', medicine_name: 'Chyawanprash Awaleha', pack_size: '500 gm' },
  { id: 'med-c08', category: 'Classical Medicine', medicine_name: 'Khadiradi Vati', pack_size: '40 tab' },
  { id: 'med-c09', category: 'Classical Medicine', medicine_name: 'Sanjivani Vati', pack_size: '40 tab' },
  { id: 'med-c10', category: 'Classical Medicine', medicine_name: 'Arogyavardhini Vati', pack_size: '40 tab' },
  { id: 'med-c11', category: 'Classical Medicine', medicine_name: 'Chandraprabha Vati', pack_size: '40 tab' },
  { id: 'med-c12', category: 'Classical Medicine', medicine_name: 'Yograj Guggulu', pack_size: '40 tab' },
  { id: 'med-c13', category: 'Classical Medicine', medicine_name: 'Kaishore Guggulu', pack_size: '40 tab' },
  { id: 'med-c14', category: 'Classical Medicine', medicine_name: 'Mahanarayan Taila', pack_size: '100 ml' },
  { id: 'med-c15', category: 'Classical Medicine', medicine_name: 'Pinda Taila', pack_size: '100 ml' },
  { id: 'med-c16', category: 'Classical Medicine', medicine_name: 'Kasis Bhasma', pack_size: '10 gm' },
  { id: 'med-c17', category: 'Classical Medicine', medicine_name: 'Shankh Bhasma', pack_size: '10 gm' },
  { id: 'med-c18', category: 'Classical Medicine', medicine_name: 'Hingwashtak Churna', pack_size: '100 gm' },
  { id: 'med-c19', category: 'Classical Medicine', medicine_name: 'Avipattikar Churna', pack_size: '100 gm' },
  { id: 'med-c20', category: 'Classical Medicine', medicine_name: 'Mahasudarshan Churna', pack_size: '100 gm' },

  // Patent Medicines & Unani Formulations
  { id: 'med-p01', category: 'Patent Medicine', medicine_name: 'Liver Protective Syrup (Hepato-Tonic)', pack_size: '200 ml' },
  { id: 'med-p02', category: 'Patent Medicine', medicine_name: 'Joint Pain Relief Liniment/Oil', pack_size: '60 ml' },
  { id: 'med-p03', category: 'Patent Medicine', medicine_name: 'Herbal Cough Syrup (Kas-Shamak)', pack_size: '100 ml' },
  { id: 'med-p04', category: 'Patent Medicine', medicine_name: 'Antacid & Digestive Syrup', pack_size: '200 ml' },
  { id: 'med-p05', category: 'Patent Medicine', medicine_name: 'Immunity Booster Drops', pack_size: '30 ml' },
  { id: 'med-p06', category: 'Patent Medicine', medicine_name: 'Anti-Diabetic Herbal Tablets', pack_size: '60 tab' },
  { id: 'med-p07', category: 'Patent Medicine', medicine_name: 'Anti-Hypertensive Capsules', pack_size: '30 cap' },
  { id: 'med-p08', category: 'Patent Medicine', medicine_name: 'Herbal Iron & Calcium Tonic', pack_size: '200 ml' },
  { id: 'med-p09', category: 'Patent Medicine', medicine_name: 'Memory & Neuro-Vitalizer Syrup', pack_size: '200 ml' },
  { id: 'med-p10', category: 'Patent Medicine', medicine_name: 'Skin Allergy Ointment', pack_size: '30 gm' },
  { id: 'med-p11', category: 'Patent Medicine', medicine_name: 'Majun Suranjan (Unani)', pack_size: '125 gm' },
  { id: 'med-p12', category: 'Patent Medicine', medicine_name: 'Sharbat Bazoori Motadil (Unani)', pack_size: '200 ml' },
  { id: 'med-p13', category: 'Patent Medicine', medicine_name: 'Roghan Badam Shirin (Unani)', pack_size: '50 ml' },
  { id: 'med-p14', category: 'Patent Medicine', medicine_name: 'Khamira Abresham Hakim Arshad Wala', pack_size: '75 gm' },
];

export const INITIAL_DYNAMIC_FORMS: DynamicForm[] = [
  {
    id: 'form-monsoon-2026',
    form_title: 'Monsoon Disease Preparedness & Stock Audit 2026',
    description: 'Special administrative audit by District Ayurvedic Officer Dehradun regarding availability of emergency fever medicines, ORS, water chlorination, and vector-borne illness preparedness.',
    is_active: true,
    created_at: '2026-08-01T10:00:00Z',
    form_fields: [
      {
        id: 'emergency_stock_status',
        label: 'Status of Emergency Fever & Diarrhea Medicines',
        type: 'select',
        options: ['Adequate (>30 days)', 'Moderate (15-30 days)', 'Critical Shortage (<15 days)'],
        required: true,
      },
      {
        id: 'water_purification_tablets',
        label: 'Chlorine / Halazone Tablets Available (Count in units)',
        type: 'number',
        required: true,
        placeholder: 'e.g. 500',
      },
      {
        id: 'dengue_chikungunya_cases',
        label: 'Total Suspected Vector-Borne Cases Treated This Month',
        type: 'number',
        required: true,
        placeholder: '0',
      },
      {
        id: 'panchakarma_equipment_operational',
        label: 'Are Panchakarma Droni & Steam Chambers Fully Operational?',
        type: 'select',
        options: ['Yes - Fully Functional', 'Partially Functional', 'Requires Maintenance', 'Not Installed'],
        required: true,
      },
      {
        id: 'inspection_remarks',
        label: 'Infrastructure Remarks / Urgent Requirements',
        type: 'textarea',
        required: false,
        placeholder: 'Mention building condition, water supply, electricity or emergency staff needs...',
      },
    ],
  },
];

export const INITIAL_MPR_REPORTS: MonthlyProgressReport[] = [
  {
    id: 'mpr-001',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    month_year: '2026-08',
    opd_count: 1420,
    panchakarma_count: 310,
    officer_name: 'Dr. Ramesh Chandra Nautiyal (AMO)',
    submitted_at: '2026-09-02T11:20:00Z',
    other_metrics: {
      opd_male: 580,
      opd_female: 690,
      opd_child: 150,
      ipd_admissions: 45,
      bed_occupancy_days: 280,
      yoga_participants: 620,
      ayush_camps_conducted: 4,
      snehan_swedan: 140,
      basti_karma: 85,
      nasya_karma: 45,
      shirodhara: 40,
      remarks: 'High patient load for joint disorders and seasonal viral fever.',
    },
  },
  {
    id: 'mpr-002',
    hospital_id: 'hosp-002',
    hospital_name: 'Government Ayurvedic Hospital, Rishikesh',
    month_year: '2026-08',
    opd_count: 1180,
    panchakarma_count: 245,
    officer_name: 'Dr. Anjali Uniyal (Sr. Medical Officer)',
    submitted_at: '2026-09-03T14:45:00Z',
    other_metrics: {
      opd_male: 510,
      opd_female: 540,
      opd_child: 130,
      ipd_admissions: 32,
      bed_occupancy_days: 190,
      yoga_participants: 480,
      ayush_camps_conducted: 3,
      snehan_swedan: 110,
      basti_karma: 65,
      nasya_karma: 38,
      shirodhara: 32,
      remarks: 'Special monsoon health awareness camps conducted along Ganga ghats.',
    },
  },
  {
    id: 'mpr-003',
    hospital_id: 'hosp-003',
    hospital_name: 'Government Ayurvedic Dispensary, Vikasnagar',
    month_year: '2026-08',
    opd_count: 760,
    panchakarma_count: 90,
    officer_name: 'Dr. Vikram Singh Rawat',
    submitted_at: '2026-09-04T10:15:00Z',
    other_metrics: {
      opd_male: 340,
      opd_female: 350,
      opd_child: 70,
      ipd_admissions: 0,
      yoga_participants: 210,
      ayush_camps_conducted: 2,
      snehan_swedan: 50,
      basti_karma: 25,
      nasya_karma: 15,
      remarks: 'Dispensed preventive kwath for rainy season.',
    },
  },
];

export const INITIAL_DEMANDS: MedicineDemandResponse[] = [
  {
    id: 'dem-001',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    medicine_id: 'med-c01',
    medicine_name: 'Triphala Churna',
    category: 'Classical Medicine',
    pack_size: '100 gm',
    requested_quantity: 150,
    officer_name: 'Dr. Ramesh Chandra Nautiyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'dem-002',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    medicine_id: 'med-c03',
    medicine_name: 'Ashwagandharishta',
    category: 'Classical Medicine',
    pack_size: '450 ml',
    requested_quantity: 80,
    officer_name: 'Dr. Ramesh Chandra Nautiyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'dem-003',
    hospital_id: 'hosp-001',
    hospital_name: 'District Ayurvedic Hospital, Tilak Road, Dehradun',
    medicine_id: 'med-p01',
    medicine_name: 'Liver Protective Syrup (Hepato-Tonic)',
    category: 'Patent Medicine',
    pack_size: '200 ml',
    requested_quantity: 120,
    officer_name: 'Dr. Ramesh Chandra Nautiyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-28T12:00:00Z',
  },
  {
    id: 'dem-004',
    hospital_id: 'hosp-002',
    hospital_name: 'Government Ayurvedic Hospital, Rishikesh',
    medicine_id: 'med-c01',
    medicine_name: 'Triphala Churna',
    category: 'Classical Medicine',
    pack_size: '100 gm',
    requested_quantity: 100,
    officer_name: 'Dr. Anjali Uniyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-29T15:30:00Z',
  },
  {
    id: 'dem-005',
    hospital_id: 'hosp-002',
    hospital_name: 'Government Ayurvedic Hospital, Rishikesh',
    medicine_id: 'med-p02',
    medicine_name: 'Joint Pain Relief Liniment/Oil',
    category: 'Patent Medicine',
    pack_size: '60 ml',
    requested_quantity: 90,
    officer_name: 'Dr. Anjali Uniyal',
    status: 'Submitted',
    batch_year: '2026-2027',
    submitted_at: '2026-08-29T15:30:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-01',
    action: 'Medicine Demand Catalog Published',
    details: 'Uploaded 20 Classical and 14 Patent items for Annual Demand 2026-2027',
    user: 'District Ayurvedic Officer (Admin)',
    timestamp: '2026-08-15T09:00:00Z',
    category: 'medicine',
  },
  {
    id: 'log-02',
    action: 'Special Survey Form Published',
    details: 'Monsoon Disease Preparedness & Stock Audit 2026 made active',
    user: 'District Ayurvedic Officer (Admin)',
    timestamp: '2026-08-16T11:30:00Z',
    category: 'form',
  },
  {
    id: 'log-03',
    action: 'Medicine Demand Submitted',
    details: 'Submitted demand for 3 items (350 total units)',
    user: 'District Ayurvedic Hospital, Tilak Road (Dr. Ramesh Chandra Nautiyal)',
    timestamp: '2026-08-28T12:00:00Z',
    category: 'medicine',
  },
  {
    id: 'log-04',
    action: 'Medicine Demand Submitted',
    details: 'Submitted demand for 2 items (190 total units)',
    user: 'Government Ayurvedic Hospital, Rishikesh (Dr. Anjali Uniyal)',
    timestamp: '2026-08-29T15:30:00Z',
    category: 'medicine',
  },
  {
    id: 'log-05',
    action: 'MPR Report Submitted',
    details: 'Submitted Monthly Progress Report for August 2026 (OPD: 1420, Panchakarma: 310)',
    user: 'District Ayurvedic Hospital, Tilak Road (Dr. Ramesh Chandra Nautiyal)',
    timestamp: '2026-09-02T11:20:00Z',
    category: 'mpr',
  },
];
